server:
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://localhost/trackapp
    username: root
    password: Liberia@1847
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  mvc:
    contentnegotiation:
      favor-path-extension: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  http:
    encoding:
      force: true
    encoding:
      charset: UTF-8

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

logging:
  level:
    org.hibernate.tool.hbm2ddl: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: log/app.log
  file:
    path: /var/log/app

server:
  error:
    include-stacktrace: never
    include-exception: true
    include-message: always
